Wealthbot\UserBundle\Entity\Group:
    type: entity
    table: group_names
    repositoryClass: Wealthbot\UserBundle\Entity\GroupRepository
    uniqueConstraints:
        unique_group_idx:
            columns: [ group_name, owner_id ]
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        owner_id:
            type: integer
            nullable: true
        group_name:
            type: string(255)
            nullable: false
        roles:
            type: array
    manyToOne:
        owner:
            targetEntity: User
            inversedBy: ownGroups
            joinColumn:
                name: owner_id
                referencedColumnName: id
                onDelete: cascade
            cascade: ['persist']
    manyToMany:
        users:
            targetEntity: User
            mappedBy: groups
    lifecycleCallbacks: {  }
